### ISSUE TITLE
paraller.for excute AdvancedAdbClient.Install 

### ISSUE THREAD

**Issue by raozhihao** [yungd1plomat/AdvancedSharpAdbClient#2]
when I use paraller.for execute advancedadbclient.install concurrently， why it lock thread.I use the command line to install concurrently, but it dont

**Comment by yungd1plomat** [comment]
Because for each thread, a new instance of AdvancedAdbClient is needed.Unfortunately AdvancedAdbClient.install does not support asynchronous calling.
You can see an example of multithreaded work [here](https://github.com/yungd1plomat/AdvancedSharpAdbClient/blob/main/Examples/MultiThreadingExample.cs)
