### ISSUE TITLE
GetFrameBufferAsync not work

### ISSUE THREAD

**Issue by majesty17** [yungd1plomat/AdvancedSharpAdbClient#29]
### What can we do for you?

System.IO.EndOfStreamException:“Unable to read beyond the end of the stream.”

**Comment by CybrZr00** [comment]
Same issue here. I've had a play about with the code but can't find a way around it. An odd thing to note is if I change headerData = new byte[52]; in FrameBuffer.cs to a larger value it gets up to returning the frameBuffer.ToImage() but then fails because it's returning to a different pool.

I was able to replicate this in both a .net 7 and .net 4.6.2 WinForms application using Android API 30.

**Comment by ilamp** [comment]
I see the issue already. Let me see if I can start a pull request tonight.

**Comment by JGouyau** [comment]
I had the same issue with "System.IO.EndOfStreamException:“Unable to read beyond the end of the stream.” The BinaryReader.Version = 2 so in  FramebufferHeader Read(byte[] data), the BinaryReader reach 52 before Apha color assignment. 

I resolve it by modified the  headerData initialisation from 52 to 56 byte. Can you modify the value in package ? 

thanks by advance and for all your work ;)

**Comment by ilamp** [comment]
I was just recently able to reproduce this. Let me see if I can find some time to work on this. I agree with @horhe4 that it should not be hardcoded.
