### ISSUE TITLE
DeviceMonitor Dispose Error

### ISSUE THREAD

**Issue by 794742233** [yungd1plomat/AdvancedSharpAdbClient#78]
### Describe the bug

```cs
var deviceMonitor = new DeviceMonitor(new AdbSocket(new IPEndPoint(IPAddress.Loopback, AdbClient.AdbServerPort)));
deviceMonitor.DeviceDisconnected += DeviceMonitor_DeviceDisconnected;
deviceMonitor.Start();
...
deviceMonitor.DeviceDisconnected -= DeviceMonitor_DeviceDisconnected;
deviceMonitor.Dispose(); // ExceptionOccurred
deviceMonitor = null;
```
If `Dispose()` is not used; There is nothing unusual about that, but it should be necessary
Then ADB is not closed and can only be closed by a manual lookup process. Without `adbServer.Shutdown();` Such function

### Steps to reproduce the bug

Run deviceMonitor and try to free it.

### Expected behavior

“`System.OperationCanceledException`"

### NuGet package version

2.5.7

### .NET Platform

.NET 7

### Platform type

Windows

### IDE

Visual Studio 2022

**Comment by wherewhere** [comment]
It is because when `Socket` async method canceled it throw `System.OperationCanceledException` on .NET Core App 7.0 or greater. This project is only supports LTS version. I am working on supporting to .NET Core App 8.0.
And it should not stop adb service because it is monitor, not manager. Others may need to do something ether when or after monitor disposed.

**Comment by wherewhere** [comment]
Fixed https://github.com/yungd1plomat/AdvancedSharpAdbClient/commit/940082c02f59dc5b691b66d1317ca82d89ddcfb1
